version: '3.7'

networks:
  set-network:
    name: set-network

services:
  set-db:
    image: postgres:14-alpine
    container_name: set-db
    hostname: set-db
    networks:
      - set-network
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: set
      POSTGRES_USER: set
      POSTGRES_PASSWORD: 7K6P,P3Q%5UC-hup
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    tty: true

  db-adminer:
    image: adminer:4-standalone
    container_name: set-adminer
    hostname: set-adminer
    networks:
      - set-network
    ports:
      - 8080:8080
    depends_on:
      - set-db
    restart: unless-stopped
    tty: true

  set-node:
    image: node:18-alpine
    container_name: set-node
    hostname: set-node
    working_dir: /usr/src/app
    user: node
    networks:
      - set-network
    ports:
      - 3000:3000
      - 4200:4200
      - 9229:9229
    volumes:
      - .:/usr/src/app
    environment:
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: Europe/Madrid
    depends_on:
      - set-db
    restart: unless-stopped
    tty: true
    # command: yarn start:all
