version: '3.8'

networks:
  set-network:
    name: set-network

services:
  set-db:
    image: postgres:15.4-alpine3.17
    container_name: set-db
    hostname: set-db
    networks:
      - set-network
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
      - ./tools/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DATABASES: ${DB_NAME},${DB_NAME_TEST}
      TZ: UTC
      PGTZ: UTC
    restart: unless-stopped
    tty: true

  set-nx:
    container_name: set-nx
    hostname: set-nx
    working_dir: /usr/src/app
    build:
      context: .
      target: serve-api
    networks:
      - set-network
    ports:
      - ${APP_PORT}:4200
      - ${API_PORT}:3000
      - ${API_DEBUG_PORT}:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MIKRO_ORM_CLI_CONFIG: apps/api/src/shared/module/config/mikro-orm.config.ts
      MIKRO_ORM_CLI_TS_CONFIG_PATH: apps/api/tsconfig.app.json
      MIKRO_ORM_CLI_ALWAYS_ALLOW_TS: 1
      MIKRO_ORM_CLI_USE_TS_NODE: 1
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: UTC
    depends_on:
      - set-db
    restart: unless-stopped
    stdin_open: true
    tty: true
