version: '3.8'

networks:
  set-network:
    name: set-network

services:
  set-db:
    image: postgres:15-alpine
    container_name: set-db
    hostname: set-db
    networks:
      - set-network
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    tty: true

  set-node:
    container_name: set-node
    hostname: set-node
    working_dir: /usr/src/app
    build:
      context: .
      target: dev
    networks:
      - set-network
    ports:
      - ${APP_PORT}:4200
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:9229
    volumes:
      - ~/.ssh:/home/user/.ssh:ro
      - ~/.gitconfig:/etc/gitconfig:ro
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: Europe/Madrid
    depends_on:
      - set-db
    restart: unless-stopped
    tty: true
