networks:
  playsetonline:
    name: playsetonline

services:
  playsetonline-db:
    image: postgres:17.0-alpine3.20
    container_name: playsetonline-db
    hostname: playsetonline-db
    networks:
      - playsetonline
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
      - ./utils/postgresql-multiple-databases.sh:/docker-entrypoint-initdb.d/generate-databases.sh:ro
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_NAMES: ${DB_NAME},${DB_NAME_TEST}
      TZ: UTC
      PGTZ: UTC
    restart: unless-stopped
    tty: true

  playsetonline-node:
    container_name: playsetonline-node
    hostname: playsetonline-node
    working_dir: /usr/src/app
    image: playsetonline-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-api
      args:
        - API_PORT=${API_PORT}
    env_file:
      - .env
    networks:
      - playsetonline
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:9229
      - ${APP_PORT}:4200
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      MIKRO_ORM_CLI_CONFIG: apps/api/src/shared/module/config/mikro-orm.config.ts
      MIKRO_ORM_CLI_TS_CONFIG_PATH: apps/api/tsconfig.app.json
      MIKRO_ORM_CLI_ALWAYS_ALLOW_TS: 1
      MIKRO_ORM_CLI_USE_TS_NODE: 1
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: UTC
    depends_on:
      - playsetonline-db
    restart: unless-stopped
    stdin_open: true
    tty: true
