version: '3.8'

networks:
  set-network:
    name: set-network

services:
  set-db:
    image: postgres:14-alpine
    container_name: set-db
    hostname: set-db
    networks:
      - set-network
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Europe/Madrid
      PGTZ: Europe/Madrid
    restart: unless-stopped
    tty: true

  db-adminer:
    image: adminer:4-standalone
    container_name: set-adminer
    hostname: set-adminer
    networks:
      - set-network
    ports:
      - 8080:8080
    depends_on:
      - set-db
    restart: unless-stopped
    tty: true

  set-node:
    image: drackp2m/node:18-alpine
    container_name: set-node
    hostname: set-node
    working_dir: /usr/src/app
    user: node
    networks:
      - set-network
    ports:
      - ${API_PORT}:${API_PORT}
      - 4200:4200
      - 9229:9229
    volumes:
      - .:/usr/src/app
    environment:
      PATH: $PATH:/usr/src/app/node_modules/.bin
      TZ: Europe/Madrid
    depends_on:
      - set-db
    restart: unless-stopped
    tty: true
    # command: yarn start:all
