version: '3.8'

services:
  set-nx:
    build:
      target: dev-attached
      args:
        USER_GID: 20
        USER_UID: 501
    volumes:
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.gnupg/pubring.kbx:/home/node/.gnupg/pubring.kbx:ro
      - ~/.gnupg/private-keys-v1.d:/home/node/.gnupg/private-keys-v1.d:ro
      - ~/.gitconfig:/home/node/.gitconfig
      - .docker/:/home/node/.p10k.zsh
      - .docker/:/home/node/.zsh_history
      - .docker/:/home/node/.zshrc
      - .docker/.local/share/zsh:/home/node/.local/share/zsh
